apiVersion: batch/v1
kind: CronJob
metadata:
  name: integration-test-product-service
spec:
  schedule: "0 0 * * *" # Adjust to your desired schedule
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: integration-test-product-service
              image: us-central1-docker.pkg.dev/moon-insurance/moon-insurance/product-service:latest
              command: ["pytest", "tests/integration-test.py"]
              resources:
                requests:
                  cpu: "250m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "256Mi"
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: product-service-db-secret
                      key: DATABASE_URL
          restartPolicy: OnFailure
