apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5005
  type: LoadBalancer # Makes the service accessible externally through a load balancer
